### Read all films with File variable
@baseUrl = http://localhost:3000
GET http://localhost:3000/films

### Create a film
POST {{baseUrl}}/films
Content-Type: application/json

{
    "title":"NvFilm",
    "duration":"150",
    "budget":"10000",
    "link":"nouveauLien"
}

### Update the film identified by 1
PATCH {{baseUrl}}/films/1
Content-Type: application/json

{
    "title":"Magic"
}

### Delete film identified by 7
DELETE {{baseUrl}}/films/7

### Update the film identified by 1
PUT {{baseUrl}}/films/7
Content-Type: application/json

{
    "title":"NV Magic",
    "duration":"400"
}